### ISSUE TITLE
Issue with month default is monday start when expanded

### ISSUE THREAD

**Issue by sadobass** [pmcarlos/flutter_clean_calendar#13]
hi~
expanded month default is monday start..
<img width="352" alt="스크린샷 2020-05-14 오후 5 08 14" src="https://user-images.githubusercontent.com/5369741/81909770-053bd980-9606-11ea-8642-c249ca1f8697.png">

and unexpanded week default is sunday..
<img width="358" alt="스크린샷 2020-05-14 오후 5 08 59" src="https://user-images.githubusercontent.com/5369741/81909791-0e2cab00-9606-11ea-8072-2925c9af3485.png">

when config startOnMonday is false.

**Comment by pmcarlos** [comment]
Thanks for reporting this, I'll fix bi the end of the week

**Comment by pmcarlos** [comment]
Fixed in 1.0.2+1, thanks for reporting
