### ISSUE TITLE
When unexpanding (shrinking), the week does not change to the week containing the selected day.

### ISSUE THREAD

**Issue by kjmclaws** [pmcarlos/flutter_clean_calendar#14]
To reproduce:
1. Have the calendar in the expanded form
2. Select a day in a week other than the one that has the current selected day.
3. Swipe up on the calendar to shrink it.
4. (NOTE) The week displayed does not have the current selected day in it.
5. Swipe left on week.
6. (NOTE) The week updates with the week before the selected day and selects the matching weekday
7. Swipe right.
8. (NOTE) The week now shows the correct week with the day selected.

**Comment by kjmclaws** [comment]
During the time that it's not showing the right week there is unexpected behavior when choosing dates( It selects the day you pick, then the week updates to where it should have been before but now not showing the selected day because that day is in the week from where you just were.

**Comment by pmcarlos** [comment]
Ok let me take a look at this, since the way weeks/months are handled changed a little bit. Will be fixed by the end of the week

**Comment by pmcarlos** [comment]
It's been fixed, please take a look
