### ISSUE TITLE
bottom part of grid view getting clipped

### ISSUE THREAD

**Issue by kamathprasad9** [pmcarlos/flutter_clean_calendar#17]
![WhatsApp Image 2020-07-10 at 10 27 46 PM](https://user-images.githubusercontent.com/54414375/87702725-64110100-c7b7-11ea-9837-7cb060903628.jpeg)

on small devices, the ending part is getting clipped. Is there a solution for this? i tried increasing the aspect ratio but it leads to a more compact calendar and hence making it difficult to tap precisely

**Comment by pmcarlos** [comment]
@kamathprasad9 did you manage to fix that? could it be something regarding the widget you were using to wrap the calendar?

**Comment by kamathprasad9** [comment]
Hey @pmcarlos!
Yes I was able to fix the issue myself. The list tile on the lower part was creating an issue on small devices, I managed to fix that. Great plugin by the way!
