### ISSUE TITLE
expansionButtonRow is not taken language localization

### ISSUE THREAD

**Issue by nairox** [pmcarlos/flutter_clean_calendar#19]
The expansionButtonRow is not taken the language when you change it

I suggest to change this line (line 283) 
Utils.fullDayFormat(selectedDate), //show date only in english
for something like this
DateFormat("EEEE MMMM dd, yyyy", widget.locale).format(_selectedDate),

That solve the problem. 

Additional, maybe to allow user to write the format they want

Thanks

**Comment by pmcarlos** [comment]
This is related with #21 right? Closing this issue for that reason
