### ISSUE TITLE
pull request from flutter calendar

### ISSUE THREAD

**Issue by limdnas** [pmcarlos/flutter_clean_calendar#2]
Hello, any plans on accepting the pending pull requests from flutter_calendar?.

here you have util pulls (first day of week for example...)
https://github.com/apptreesoftware/date_utils/pulls

and here...
https://github.com/apptreesoftware/flutter_calendar/pulls

**Comment by pmcarlos** [comment]
What do you mean?

**Comment by jmsandamil** [comment]
flutter_calendar has new improvements that maybe you could add to this calendar

**Comment by pmcarlos** [comment]
Let me check on them, next week I'll be adding more features. Please leave me a comment with the ones you think are priorities

**Comment by pmcarlos** [comment]
Please let me know what do you want to be improved. BTW we are not the same maintainers
