### ISSUE TITLE
Dark theme Not supported 

### ISSUE THREAD

**Issue by mdavidkhan** [pmcarlos/flutter_clean_calendar#22]
Dark theme issue in calendar, it is not workable in dark mode. and there is no option to change the text colour of normal days.

**Comment by Subkowiaki** [comment]
Hello, you can fix this problem by editing the file 'calendar_tile.dart'. 
(external Libaries > Dart Packages > flutter_clean_calendar-[version of clean calendar]> calendar_tile.dart) 
Line 79 (colour of normal days)

[pt-br]

 Olá! você consegue arrumar este erro editando o arquivo do tile do calendario no seguinte caminho: 
(external Libaries > Dart Packages > flutter_clean_calendar-[version of clean calendar]> calendar_tile.dart) 
na linha 79 esta a configuração dos dias normais
