### ISSUE TITLE
selecting a day in the next month

### ISSUE THREAD

**Issue by islmansour** [pmcarlos/flutter_clean_calendar#24]
Hi
Thanks for this package , very helpful!

I found a problem, here is how you reproduce:

Today is Aug 30th.
My calendar shows correct month name value in the top (between the two arrows), i.e. August.
If I select September 1st, the calendar is updated, but the month name value in the top (between the two arrows) still shows August.

Thanks

**Comment by usernamekk** [comment]
I have the same issue. Were u able to solve this issue. Thanks.

**Comment by usernamekk** [comment]
on week ( i.e !expanded), if I use Sunday as the week start, when click on Sunday date, it takes me out of that week. How can I solve this pls.

**Comment by pmcarlos** [comment]
Should be working now

**Comment by usernamekk** [comment]
yes working. Thanks
