### ISSUE TITLE
How to customize dates with different colors.

### ISSUE THREAD

**Issue by usernamekk** [pmcarlos/flutter_clean_calendar#28]
`final Data = {
DateTime(2020, 10, 10): [{'name': 'Event A',  'isDone': true, 'color':'red'},],
DateTime(2020, 10, 11): [{'name': 'Event A',  'isDone': false, 'color':'white'},],
DateTime(2020, 10, 12): [{'name': 'Event A',  'isDone': true, 'color':'blue'},],
};`

Something similar to this. Thanks.
![calendar](https://user-images.githubusercontent.com/28014560/96002763-64aa4980-0e31-11eb-9c70-9e645210d0aa.jpg)

**Comment by usernamekk** [comment]
Thank God. I got it. Problem Solved perfectly.

**Comment by pmcarlos** [comment]
Good to know, thanks for letting me know!
