### ISSUE TITLE
Today's event not showing until you tap on the date.

### ISSUE THREAD

**Issue by usernamekk** [pmcarlos/flutter_clean_calendar#30]
How is it possible to always see today's event loaded at start up without clicking the date.

**Comment by usernamekk** [comment]
ok solved.

By using this at initstate.
_handleNewDate(DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day));

**Comment by pmcarlos** [comment]
@usernamekk Do you mind pleasing creating a PR with this?

**Comment by usernamekk** [comment]
I have a project. If that is what you mean.

**Comment by usernamekk** [comment]
I have a project. If that is what you mean.

**Comment by kespaldon** [comment]
Hey, do you mind providing a more detailed example on how to implement this? Not sure where to use `_handleNewDate`

**Comment by usernamekk** [comment]
U can email me for more details

**Comment by kespaldon** [comment]
Why email? Why not post it here so everyone can see? 🧐

**Comment by usernamekk** [comment]
Ok will do that later. Busy
