### ISSUE TITLE
Is Expanded Don´t work  dynamically

### ISSUE THREAD

**Issue by TicketMarketTecnologia** [pmcarlos/flutter_clean_calendar#31]
Calendar does not change IsExpanded dynamically:

I analyzed the code and probably uses InitState to set the variable isExpanded
again..

 void initState () {
    super.initState ();

    isExpanded = widget? .isExpanded ?? false;

 and therefore if the Calendar is still built and has only the isExpanded variable changed, initstate will not be run again.

Just use widget.isExpanded in place of isExpanded throughout the lib widget.

**Comment by zvikarp** [comment]
Hi @TicketMarketTecnologia I opened a PR on this issue (also needed to change the state dynamically).
If you wish, you can use my fork until the PR is excepted (or make your own).

```
  flutter_clean_calendar:
    git:
      url: https://github.com/zvikarp/flutter_clean_calendar.git
```

**Comment by TicketMarketTecnologia** [comment]
@zvikarp 
Good job! I was busy and realized that the lib was not being updated.

I'm going to use your Fork to fix this. I saw some other small problems that I must report on shortly.

Thank you for your help.
