### ISSUE TITLE
Support null-safety

### ISSUE THREAD

**Issue by zvikarp** [pmcarlos/flutter_clean_calendar#35]
Hi, thanks for the awesome package.

Dart 2.12 and flutter 2.0.0 are now in stable with the null-safety feature.

Migrating this package to null-safety would help a lot. :)

Here's an official guide from dart doc
https://dart.dev/null-safety/migration-guide

I would love to contribute and help with the migration.

**Comment by pmcarlos** [comment]
Hi @zvikarp any help is welcome, we have migrated and updated a lot of the package, do you mind taking a closer look at the current status of the package please?

**Comment by zvikarp** [comment]
Hey @pmcarlos hope you are doing well, I see you have merged [my PR](https://github.com/pmcarlos/flutter_clean_calendar/pull/33) about two weeks ago, and you have bumped the version so all looks great! 

My bad I forgot to close this issue, and thank you for the response.
