### ISSUE TITLE
When startonMonday is false. Sunday calendar 📆 does not show, if not expanded

### ISSUE THREAD

**Issue by usernamekk** [pmcarlos/flutter_clean_calendar#36]
![Screenshot_20210411-013320](https://user-images.githubusercontent.com/28014560/114288393-6747cd80-9a67-11eb-8b70-fa5bfa2ccb00.png)

The date is Sunday 11 April but doesn't show on calendar.

**Comment by rwbr** [comment]
I fixed this in my fork of this project with commit https://github.com/rwbr/flutter_neat_and_clean_calendar/commit/79453e5d236b239b9e0cf86763ba22713e45e314
