### ISSUE TITLE
How to change today color?

### ISSUE THREAD

**Issue by iamaz007** [pmcarlos/flutter_clean_calendar#44]
I want to change this red/orange color of current day. I changed color of past/future days with property. **selectedColor:** but How i can change color of current day? 
I know there is a property **todayColor** but it is changing only text color of that day, not the whole container/card (widget).
![image](https://user-images.githubusercontent.com/53218172/146559844-919cee14-b17b-4a3d-8e80-949b4ddcf225.png)

**Comment by rwbr** [comment]
Please read the documentation. The library has a parameter for that:
```dart
/// [todayColor] this is the color of the date of today
```

**Comment by rwbr** [comment]
Sorry, my fault. The parameter to set the color of the circle is:
```dart
/// [selectedColor] is a [Color] used for displaying the selected tile
```
There is one exception though: If the selected date is today, then the circle is always red. On all other days it uses the color you specify with this parameter.

**Comment by iamaz007** [comment]
This was my solution
 #![image](https://user-images.githubusercontent.com/53218172/152632240-4f439621-a2f4-4ab5-a86a-35948c22dad1.png)
![image](https://user-images.githubusercontent.com/53218172/152632250-1bc42558-ba2a-4fa1-a7af-1196c5aab63b.png)
in this way I can add different colors for **Today's Circle** and **other days**
