### ISSUE TITLE
Realtime changes events from Firestore

### ISSUE THREAD

**Issue by ben55j** [pmcarlos/flutter_clean_calendar#47]
Hello, 

Thank you for this great package! 
I was wondering if we could use it we with events extract from Firestore in real time ?
Do you have any example that could help me in this way ?

Many thanks, 
Ben

**Comment by rwbr** [comment]
Maybe pulling the events form FireStore, mapping them to `CleanCalendarEvent`, adding them to a `Map<DateTime, List<CleanCalendarEvent>> ` and then initializing the calendar widget with this map?
