### ISSUE TITLE
Package Call Example

### ISSUE THREAD

**Issue by ederluca** [pmcarlos/flutter_clean_calendar#5]
Good Morning

I'm trying to use flutter_calendar_clean, but I'm not getting it already installed the package in my application, made the import with the command below:
import 'package: flutter_clean_calendar / flutter_clean_calendar.dart';

But in the documentation I didn't find a way to invoke the calendar I tried basically as follows:

body: Center (child: Calendar ()),

But unfortunately presented error believe I have a correct do so could give me a simple example of how to invoke this package?

**Comment by pmcarlos** [comment]
Hi please take a look at the example folder `example/lib/main.dart` 
You have to import like: 'import `package:flutter_clean_calendar/flutter_clean_calendar.dart';`
Please send me the errors you are facing
