### ISSUE TITLE
Issue with a useless line of previous calendar

### ISSUE THREAD

**Issue by fmfuerte** [pmcarlos/flutter_clean_calendar#6]
hello it seems that when the month starts at a sunday it will still print a whole line of the previous greyed-out month. this should not be the case as it takes a whole extra week line

**Comment by pmcarlos** [comment]
> hello it seems that when the month starts at a sunday it will still print a whole line of the previous greyed-out month. this should not be the case as it takes a whole extra week line

Hi any help on this?

**Comment by pmcarlos** [comment]
I added the chance to start on sunday or monday, please give it a try
