### ISSUE TITLE
Please improve the dependency of date_util  

### ISSUE THREAD

**Issue by AkinobuKamiya** [pmcarlos/flutter_clean_calendar#8]
A better calendar than any other calendar
However, it is a pity that the dependency of date_util is intl0.15.0
Can you improve this?

**Comment by pmcarlos** [comment]
Any suggestion for another library? At the moment I am using this fo get last day of week, first day of week, daysinmonth, days in . given range, etc.
Would you be able to open a PR and extract these methods from de `date_utils` library?

**Comment by pmcarlos** [comment]
Can you please give it a try again if you want?
