### ISSUE TITLE
Error when update version of flutter

### ISSUE THREAD

**Issue by haohmaruru** [pmcarlos/flutter_clean_calendar#9]
Hi ad,
When i update flutter version v1.12.13+hotfix.5-stable i see some error:

Because no versions of flutter_clean_calendar match >1.0.1 <2.0.0 and flutter_clean_calendar 1.0.1 depends on date_utils ^0.1.0+2, flutter_clean_calendar ^1.0.1 requires date_utils ^0.1.0+2.

Because date_utils 0.1.0+2 depends on intl ^0.15.0 and no versions of date_utils match >0.1.0+2 <0.2.0, date_utils ^0.1.0+2 requires intl ^0.15.0.

Thus, flutter_clean_calendar ^1.0.1 requires intl ^0.15.0.

So, because hesty_home_staff depends on both intl ^0.16.0 and flutter_clean_calendar ^1.0.1, version solving failed.
pub get failed (1; So, because hesty_home_staff depends on both intl ^0.16.0 and flutter_clean_calendar ^1.0.1, version solving failed.)

Can you help me resolve it.

**Comment by pmcarlos** [comment]
Hi can you give it a try again? Sorry for late reply
